[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "cd sftp://opi/data"
desc = "Go to network storage"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
